# Generated by Django 5.0.6 on 2024-05-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rswllapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='mbile',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
