# Generated by Django 5.0.6 on 2024-05-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rswllapp', '0002_alter_inquiry_mbile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcat',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
