# Generated by Django 5.0.6 on 2024-05-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rswllapp', '0003_remove_product_subcat_delete_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='mbile',
            new_name='mobile',
        ),
    ]
