# Generated by Django 5.0.6 on 2024-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rswllapp', '0004_rename_mbile_inquiry_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dis',
            field=models.TextField(),
        ),
    ]
