# Generated by Django 5.0.6 on 2024-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rswllapp', '0007_alter_product_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dis',
            field=models.TextField(null=True),
        ),
    ]
