# Generated by Django 5.0.6 on 2024-05-24 09:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rswllapp', '0010_alter_product_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dis',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=True),
        ),
    ]
